name: releases-build

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  FLUTTER-VERSION: '3.32.5'

jobs:
  windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Instalar o Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          flutter-version: ${{ env.FLUTTER-VERSION }}
          channel: stable
      
      - name: Exibir a versao instalada do Flutter
        run: flutter --version

      - name: Informacoes e configuracoes do Flutter
        run: flutter doctor -v

      - name: Instalar dependências do Flutter
        run: flutter pub get

      - name: Executar Build para Windows
        run: flutter build windows --release


      - name: Compressão dos artefatos
        run: Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath windows-x64.zip 

      - name: Upload dos artefatos do build
        uses: softprops/action-gh-release@v2
        with:
          files: windows-x64.zip
          tag_name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || github.sha }}
          name: Release ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || github.sha }}
          draft: ${{ startsWith(github.ref, 'refs/tags/') == false }}
          prerelease: false

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Instalando dependencias
        run: |
          sudo apt-get update -y  
          sudo apt-get install -y ninja-build libgtk-3-dev 

      - name: Instalar o Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          flutter-version: ${{ env.FLUTTER-VERSION }}
          channel: stable

      - name: Exibir a versao instalada do Flutter
        run: flutter --version

      - name: Informacoes e configuracoes do Flutter
        run: flutter doctor -v

      - name: Instalar dependências do Flutter
        run: flutter pub get

      - name: Executar Build para Linux
        run: flutter build linux --release

      - name: Compressão dos artefatos
        run: tar -czvf linux-x64.tar.gz -C build/linux/x64/release/bundle .

      - name: Upload dos artefatos do build
        uses: softprops/action-gh-release@v2
        with:
          files: linux-x64.tar.gz
          tag_name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || github.sha }}
          name: Release ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || github.sha }}
          draft: ${{ startsWith(github.ref, 'refs/tags/') == false }}
          prerelease: false